### ISSUE TITLE
fails on Macos Mojave

### ISSUE THREAD

**Issue by moshix** [wrljet/hercules-helper#9]
20:31:46~/herctest ~/hercules-helper/hyperion-buildall.sh --auto
/Users/moshe/hercules-helper/hyperion-buildall.sh: line 208: shopt: globstar: invalid shell option name
/Users/moshe/hercules-helper/hyperion-buildall.sh: line 770: syntax error in conditional expression: unexpected token `('
/Users/moshe/hercules-helper/hyperion-buildall.sh: line 770: syntax error near `*@(M'
/Users/moshe/hercules-helper/hyperion-buildall.sh: line 770: `            if [[ "$(< /proc/version)" == *@(Microsoft|WSL)* ]]; then'

**Comment by wrljet** [comment]
I have created a macOS Mojave in VMware and am looking into this.

Bill

**Comment by wrljet** [comment]
I have created a macOS Mojave in VMware and am looking into this.
I never touched an Apple Mac before this. 

I have the builder working, and am now testing the changes to ensure they haven't broken other systems.

Bill

**Comment by wrljet** [comment]
Moshe,

OK, this has been updated to work on macOS.  I did the work on Mojave 10.14.6 under VMware.

Several things are changed:
- modified where needed to work with the older version of Bash on the Mac.
- autoconf/automake/libtool have been updated to modern versions that understand macOS.
The versions currently in the SDL-Hyperion-390 sources are 10 to 15 years old.
- assorted changes to the scripts to add macOS support

A new script has been added called `macOS-prerequisites`.  This will install the Xcode Command Line Tools
and Homebrew package manager, if they are not already on your system.

This experimental work is in a branch called "mojave".  A similar branch is in my fork of SDL-Hyperion-390.
Those changes will be push upstream after this has been thoroughly tested on all the systems I check.

A `hercules-helper.conf` config file included in this branch will direct the main script to
git clone Hyperion from my Github fork/branch rather than the default of SDL-Hyperion-390.

To get this work: (you will need to erase your existing `/Users/moshe/hercules-helper` folder.
` git clone -b mojave https://github.com/wrljet/hercules-helper.git`

If git is not already installed on your system, you can grab this branch with a browser:
`https://github.com/wrljet/hyperion/archive/refs/heads/mojave.zip`

Then run similar to before, but you may need the prerequisite step.
`hyperion-buildall.sh` will tell you if that step is needed and you haven't run it.

```
cd ~/herctest
~/hercules-helper/macOS-prerequisites.sh
~/hercules-helper/hyperion-buildall.sh --auto
```

Let me know what happens.
Bill

**Comment by moshix** [comment]
thanks. I will try it out and report

**Comment by moshix** [comment]
worked. 

thanks a lot

M

**Comment by wrljet** [comment]
Cool!

Can you zip up and send me the log file, please.
I'd like to inspect it for trouble to help improve this rig.

Bill

**Comment by moshix** [comment]
pls send me an email and I will email you the log.

**Comment by wrljet** [comment]
bill@wrljet.com

**Comment by wrljet** [comment]
Works now also on macOS 10.15 Catalina.
